#
#     /\_____/\
#    /  o   o  \
#   ( ==  ^  == )
#    )         (
#   (           )
#  ( (  )   (  ) )
# (__(__)___(__)__)
#
# Installation:
#   poetry install
#
# References:
#   - pyproject.toml: https://packaging.python.org/en/latest/
#   - poetry        : https://python-poetry.org/docs/

[project]
name            = "torchdiffeq"
version         = "0.2.5"
authors         = [
    { name = "Ricky Tian Qi Chen", email = "rtqichen@cs.toronto.edu" },
]
description     = "ODE solvers and adjoint sensitivity analysis in PyTorch."
readme          = "README.md"
license         = "MIT"
license-files   = ["LICENSE"]
keywords        = []
classifiers     = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
requires-python = ">=3.12,<3.14"
dependencies    = [
    "torch>=1.5.0",
    "scipy>=1.4.0",
]

[project.urls]
Homepage = "https://github.com/rtqichen/torchdiffeq"

[tool.poetry]
packages = [
    { include = "torchdiffeq", from = "." },
]
include  = []
exclude  = []

[build-system]
requires      = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"
